name: stylish_dialog
description: Stylish Alert Dialogs for Flutter.
version: 0.0.3
homepage: https://github.com/MarsadMaqsood/StylishDialogFlutter.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

codecov:
  token: 25ddd5a4-9fd3-444c-9d5b-d50723eec215