name: stylish_dialog
description: A collection of stylish animated dialogs like Normal, Progress, Success, Info, Warning, and Error for flutter.
version: 0.1.2
homepage: https://github.com/MarsadMaqsood/StylishDialogFlutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter